version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

volumes:
  postgres_data:
