FROM postgres:13-alpine

ENV POSTGRES_USER=admin \
    POSTGRES_PASSWORD=password \
    POSTGRES_DB=fastapi_db

COPY init.sql /docker-entrypoint-initdb.d/

HEALTHCHECK CMD pg_isready -U $POSTGRES_USER

EXPOSE 5432