version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/fastapi_db
    depends_on:
      - postgres

volumes:
  postgres_data:
